# Generated by Django 3.1.5 on 2021-01-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questino_text',
            new_name='question_text',
        ),
    ]
